### ISSUE TITLE
Not working with the Altair library

### ISSUE THREAD

**Issue by rezpe** [martgnz/madrid-atlas#2]
Hi,

   Thanks for the great work. I am testing the topojson provided in the help, but it does not work with the python library altair. Here's the code I am using:

```python
import altair as alt
from vega_datasets import data
url = "https://martingonzalez.net/madrid-tracts.v1.json"
counties = alt.topo_feature(url, 'census_tracts')

alt.Chart(counties).mark_geoshape().encode().properties(
    width=300,
    height=300
)
```

This is the result I get:
![image](https://user-images.githubusercontent.com/765458/45347983-ab237f00-b5ad-11e8-8cef-436b0dc2f7ca.png)

The same code used for the json in es-atlas works fine. Please, couild you confirm you have the same problem. I am willing to help to find a solution !

Thanks

**Comment by martgnz** [comment]
I think Altair fails to render the map correctly because this TopoJSON is already projected. You can use the `identity` projection described [here](https://altair-viz.github.io/user_guide/data.html#projections), or reproject the coordinates to WGS84 with GDAL as described [here](https://ben.balter.com/2013/06/26/how-to-convert-shapefiles-to-geojson-for-use-on-github/).

**Comment by rezpe** [comment]
Thanks

**Comment by martgnz** [comment]
I'm going to close this as this seems to be the issue. Let me know if it doesn't work and I'll reopen the issue.

I will think about including a file with WGS84 coordinates for the next release!
